# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HKAlbumPicker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'YXKitOC', :git => 'https://gitee.com/zaaqqq/YXKitOC.git', :tag => '2.2.7'
  pod 'Masonry'
  # Pods for HKAlbumPicker

  target 'HKAlbumPickerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HKAlbumPickerUITests' do
    # Pods for testing
  end

end
